server:
  port: 8080
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:9500/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'