server:
  port: 9500
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    # 心跳间隔
    lease-renewal-interval-in-seconds: 30
    # 心跳过期间隔
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    # 自我保护阈值
    renewal-percent-threshold: 0.85
    # 自我保护模式
    enable-self-preservation: false
#    renewal-threshold-update-interval-ms: 0
#    eviction-interval-timer-in-ms: 0
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 60000
#    wait-time-in-ms-when-sync-empty: 0
#    renewal-percent-threshold: 0.85
#    renewal-threshold-update-interval-ms:
