server:
  port: 9510
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: root
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
