server:
  port: 9590
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/
redis:
  host: 127.0.0.1
    port: 6379

cloud:
  gateway:
    routes:
    # 请求路径匹配
      - id: path_route
    uri: http://www.lhdyx.cn
      predicates:
        - Path=/lhd/**
      # 请求地址携带lhd的,则转发
      # 加上StripPrefix=1，否则转发到后端服务时会带上前缀
        filters:
          - StripPrefix=1
