server:
  port: 9510
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:9500/eureka
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          version: 1.0.0
          search-locations: classpath:/configs/core/,classpath:/configs/mall/
